In [11]:
import pandas as pd
import numpy as np
wdr =  (
        pd.read_csv('2009_2020_annual_surgical_wait_times.csv')
        .rename(columns={'FISCAL_YEAR':'year', 'HEALTH_AUTHORITY': 'HA', 'HOSPITAL_NAME':'hosp', 'PROCEDURE_GROUP': 'prcd', 'WAITING':'waiting', 'COMPLETED': 'comp', 'COMPLETED_50TH_PERCENTILE': 'median_wait_w', 'COMPLETED_90TH_PERCENTILE':'wait_90_w'})
        .dropna()
)
wdr.head()

,year,HA,hosp,prcd,waiting,comp,median_wait_w,wait_90_w
0,2009/10,All Health Authorities,All Facilities,Abdominoplasty,52,100,9.1,42.6
1,2009/10,All Health Authorities,All Facilities,All Other Procedures,"1,347","6,287",4.0,17.1
2,2009/10,All Health Authorities,All Facilities,All Procedures,"72,056","219,284",5.3,24.3
3,2009/10,All Health Authorities,All Facilities,Aortic Aneurysm Repair,96,365,3.7,13.5
4,2009/10,All Health Authorities,All Facilities,Appendectomy,19,88,3.7,9.1

In [13]:
wdr.describe()

       median_wait_w     wait_90_w
count   30266.000000  30266.000000
mean        7.421086     22.002425
std         7.163949     17.150503
min         0.000000      0.000000
25%         3.100000     10.300000
50%         5.300000     18.000000
75%         9.000000     29.500000
max       142.600000    256.100000